DEPARTMENTS = [
    ("AKKD", "Akkadian"),
    ("AMER", "American Culture"),
    ("ASLG", "American Sign Language"),
    ("AANL", "Ancient Anatolian Languages"),
    ("ANCM", "Ancient Mediterranean World"),
    ("ANCC", "Anesthesia/Critical Care"),
    ("AASR", "Anthro/Sociology of Religion"),
    ("ANTH", "Anthropology"),
    ("ADSP", "Applied Data Science"),
    ("ARAB", "Arabic"),
    ("ARAM", "Aramaic"),
    ("ARKE", "Archaeology"),
    ("ARCH", "Architectural Studies"),
    ("ARME", "Armenian"),
    ("ARTH", "Art History"),
    ("ASTR", "Astronomy/Astrophysics"),
    ("BANG", "Bangla"),
    ("BASQ", "Basque"),
    ("BIBL", "Biblical Studies"),
    ("BPRO", "Big Problems"),
    ("BCMB", "Biochemistry/Molecular Biology"),
    ("BIOS", "Biological Sciences (College)"),
    ("BSDG", "Biological Sciences (Graduate)"),
    ("BMSC", "Biomedical Sciences"),
    ("BPHS", "Biophysical Sciences"),
    ("BCSN", "Bosnian/Croatian/Serbian"),
    ("BUSN", "Business"),
    ("CABI", "Cancer Biology"),
    ("CATA", "Catalan"),
    ("CCCT", "Center for Contemporary Theory"),
    ("CHEM", "Chemistry"),
    ("CCTE", "Chicago Center for Teaching"),
    ("CHST", "Chicago Studies"),
    ("CHIN", "Chinese"),
    ("CMST", "Cinema/Media Studies"),
    ("CLCV", "Classical Civilization"),
    ("CLAS", "Classics"),
    ("CCSG", "Climate and Sustainable Growth"),
    ("CCTS", "Clinical/Translational Science"),
    ("COGS", "Cognitive Science"),
    ("CAPP", "Comp Analysis/Public Pol"),
    ("CHDV", "Comparative Human Development"),
    ("CMLT", "Comparative Literature"),
    ("CPNS", "Computational Neuroscience"),
    ("MACS", "Computational Social Science"),
    ("CAAM", "Computational and Applied Math"),
    ("CMSC", "Computer Science"),
    ("MPCS", "Computer Science Masters"),
    ("CHSS", "Conceptual/Hist Studies of Sci"),
    ("CRWR", "Creative Writing"),
    ("CZEC", "Czech"),
    ("DATA", "Data Science"),
    ("DEMS", "Democracy Studies"),
    ("DVBI", "Developmental Biology"),
    ("DIGS", "Digital Humanities"),
    ("CDIN", "Disciplinary Innovation"),
    ("EALC", "East Asian Languages/Civ"),
    ("ECEV", "Ecology/Evolution"),
    ("ECON", "Economics"),
    ("ECMA", "Economics (ECMA)"),
    ("EDSO", "Education and Society"),
    ("EGPT", "Egyptian"),
    ("EMED", "Emergency Medicine"),
    ("ELIN", "English Language Institute"),
    ("ENGL", "English Language/Literature"),
    ("CEGU", "Environment/Geog/Urbanization"),
    ("ENSC", "Environmental Sciences"),
    ("ENST", "Environmental/Urban Studies"),
    ("EVOL", "Evolutionary Biology"),
    ("FMED", "Family Medicine"),
    ("FINM", "Financial Mathematics"),
    ("FREN", "French"),
    ("FNDL", "Fundamentals: Issues/Texts"),
    ("GEEZ", "Ge'ez"),
    ("GNSE", "Gender/Sexuality Studies"),
    ("SLAV", "General Slavic"),
    ("GENE", "Genetics"),
    ("GISC", "Geographic Information Science"),
    ("GEOG", "Geographical Sciences"),
    ("GEOS", "Geophysical Sciences"),
    ("GRMN", "German"),
    ("GLST", "Global Studies"),
    ("GREK", "Greek"),
    ("HIPS", "HIPS"),
    ("KREY", "Haitian Kreyol"),
    ("HLTH", "Health and Society"),
    ("HEBR", "Hebrew"),
    ("HIND", "Hindi"),
    ("HIST", "History"),
    ("HCHR", "History of Christianity"),
    ("HIJD", "History of Judaism"),
    ("HREL", "History of Religions"),
    ("HGEN", "Human Genetics"),
    ("HMRT", "Human Rights"),
    ("HUMA", "Humanities"),
    ("IMMU", "Immunology"),
    ("IRHU", "Inquiry/Research in Humanities"),
    ("ISTP", "Interdisc Scientist Training"),
    ("INRE", "International Relations"),
    ("ISLM", "Islamic Studies"),
    ("ITAL", "Italian"),
    ("JAPN", "Japanese"),
    ("JWSC", "Jewish Studies"),
    ("KNOW", "KNOW"),
    ("KORE", "Korean"),
    ("EXAM", "Language Reading Exam"),
    ("LATN", "Latin"),
    ("LACS", "Latin Amer/Caribbean Studies"),
    ("LLSO", "Law/Letters/Society"),
    ("LAWS", "Laws"),
    ("LING", "Linguistics"),
    ("MSBI", "M.S. in Biomedical Informatics"),
    ("MAPH", "MAPH (MA in Humanities)"),
    ("MAPS", "MAPSS (MA in Social Sciences)"),
    ("MDVS", "MDIV Special Courses"),
    ("MLAP", "Master of Liberal Arts"),
    ("MATH", "Mathematics"),
    ("MADD", "Media Arts and Design"),
    ("MPHY", "Medical Physics"),
    ("MEDC", "Medicine"),
    ("MDVL", "Medieval Studies"),
    ("MICR", "Microbiology"),
    ("NEHC", "Middle Eastern Studies (NEHC)"),
    ("MOGK", "Modern Greek"),
    ("MENG", "Molecular Engineering"),
    ("MGCB", "Molecular Genetics/Cell Bio"),
    ("MOMN", "Molecular Metabolism/Nutrition"),
    ("MUSI", "Music"),
    ("NEAA", "Near Eastern Art/Archeology"),
    ("NELC", "Near Eastern Languages/Civ"),
    ("NURB", "Neurobiology"),
    ("NURL", "Neurology"),
    ("NSCI", "Neuroscience"),
    ("NSUR", "Neurosurgery"),
    ("NORW", "Norwegian"),
    ("OBGY", "Obstetrics/Gynecology"),
    ("OPTH", "Ophthalmology/Visual Sciences"),
    ("ORGB", "Organismal Biology/Anatomy"),
    ("ORTH", "Orthopaedic Surgery/Rehab Med"),
    ("PARR", "Parrhesia Public Discourse"),
    ("PATH", "Pathology"),
    ("PEDS", "Pediatrics"),
    ("PERS", "Persian"),
    ("PHIL", "Philosophy"),
    ("DVPR", "Philosophy of Religions"),
    ("PHSC", "Physical Science"),
    ("PSMS", "Physical Sciences Masters"),
    ("PHYS", "Physics"),
    ("POLI", "Polish"),
    ("PECO", "Political Economy"),
    ("PLSC", "Political Science"),
    ("PORT", "Portuguese"),
    ("MSPH", "Precision Health"),
    ("PSCR", "Psychiatry"),
    ("PSYC", "Psychology"),
    ("PUBD", "Pub Dialogue/Civic Leadership"),
    ("PBHS", "Public Health Sciences"),
    ("PBPL", "Public Policy Studies (PBPL)"),
    ("PPHA", "Public Policy Studies (PPHA)"),
    ("PUBT", "Public Thinking"),
    ("QMSA", "Quantitative Social Analysis"),
    ("RDIN", "Race, Diaspora,and Indigeneity"),
    ("RCON", "Radiation/Cellular Oncology"),
    ("RADI", "Radiology"),
    ("RLVC", "Religion/Lit/Visual Culture"),
    ("RAME", "Religions in America"),
    ("RETH", "Religious Ethics"),
    ("RELP", "Religious Leadership/Practice"),
    ("RLST", "Religious Studies"),
    ("RENS", "Renaissance Studies"),
    ("RLLT", "Romance Languages/Literature"),
    ("RUSS", "Russian"),
    ("REES", "Russian/East European Studies"),
    ("PRAC", "SSA Field Practicum"),
    ("SANS", "Sanskrit"),
    ("SCPD", "Science Comm/Public Discourse"),
    ("SIGN", "Signature Courses"),
    ("SOSC", "Social Sciences"),
    ("SSAD", "Social Service Administration"),
    ("SCTH", "Social Thought"),
    ("SOCI", "Sociology"),
    ("SALC", "South Asian Languages/Civ"),
    ("SPAN", "Spanish"),
    ("DVSC", "Special Courses in Divinity"),
    ("STAT", "Statistics"),
    ("SABR", "Study Abroad"),
    ("SUMR", "Sumerian"),
    ("SURG", "Surgery"),
    ("SWAH", "Swahili"),
    ("TAPS", "Theater/Performance Studies"),
    ("THEO", "Theology"),
    ("TBTN", "Tibetan"),
    ("TTIC", "Toyota Tech Inst at Chicago"),
    ("TURK", "Turkish"),
    ("UKRA", "Ukranian"),
    ("URDU", "Urdu"),
    ("ARTV", "Visual Arts"),
    ("WRIT", "Writing"),
    ("YDDH", "Yiddish"),
]
